# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: fedora/bind-dyndb-ldap.spec

# add or remove files that should be synced
synced_files:
    - fedora/bind-dyndb-ldap.spec
    - .packit.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: bind-dyndb-ldap
# downstream (Fedora) RPM package name
downstream_package_name: bind-dyndb-ldap

upstream_ref: bind-9.16-sg-start

upstream_project_url: https://pagure.io/bind-dyndb-ldap/
